services:
  webui:
    build:
      context: .
    image: ghcr.io/beecave-homelab/transcriptor:latest
    restart: unless-stopped
    ports:
      - "5050:5050"
    volumes:
      - ./uploads:/app/uploads
      - ./transcripts:/app/transcripts
    # environment:
      # - VIRTUAL_ENV=/app/venv